# Generated by Django 3.2.3 on 2021-06-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='userId',
        ),
        migrations.AddField(
            model_name='comments',
            name='userName',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
